services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: form_builder
      POSTGRES_PASSWORD: form_builder
      POSTGRES_DB: form_builder
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5433:5432"
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
