import type {
  ButtonDesignTokens,
  ButtonTokenSections,
} from "@primeuix/themes/types/button";

export const root: ButtonTokenSections.Root = {
  borderRadius: "{form.field.border.radius}",
  roundedBorderRadius: "2rem",
  gap: "0.5rem",
  paddingX: "{form.field.padding.x}",
  paddingY: "{form.field.padding.y}",
  iconOnlyWidth: "2.5rem",
  sm: {
    fontSize: "{form.field.sm.font.size}",
    paddingX: "{form.field.sm.padding.x}",
    paddingY: "{form.field.sm.padding.y}",
    iconOnlyWidth: "2rem",
  },
  lg: {
    fontSize: "{form.field.lg.font.size}",
    paddingX: "{form.field.lg.padding.x}",
    paddingY: "{form.field.lg.padding.y}",
    iconOnlyWidth: "3rem",
  },
  label: {
    fontWeight: "500",
  },
  raisedShadow:
    "0 3px 1px -2px rgba(0, 0, 0, 0.2), 0 2px 2px 0 rgba(0, 0, 0, 0.14), 0 1px 5px 0 rgba(0, 0, 0, 0.12)",
  focusRing: {
    width: "{focus.ring.width}",
    style: "{focus.ring.style}",
    offset: "{focus.ring.offset}",
  },
  badgeSize: "1rem",
  transitionDuration: "{form.field.transition.duration}",
};

export const colorScheme: ButtonTokenSections.ColorScheme = {
  light: {
    root: {
      primary: {
        background: "{primary.color}",
        hoverBackground: "{primary.hover.color}",
        activeBackground: "{primary.active.color}",
        borderColor: "{primary.color}",
        hoverBorderColor: "{primary.hover.color}",
        activeBorderColor: "{primary.active.color}",
        color: "{primary.contrast.color}",
        hoverColor: "{primary.contrast.color}",
        activeColor: "{primary.contrast.color}",
        focusRing: {
          color: "{primary.color}",
          shadow: "none",
        },
      },
      // secondary: {
      //   background: "{uvGreen.300}",
      //   hoverBackground: "{uvGreen.200}",
      //   activeBackground: "{uvGreen.300}",
      //   borderColor: "{uvGreen.300}",
      //   hoverBorderColor: "{uvGreen.200}",
      //   activeBorderColor: "{uvGreen.300}",
      //   color: "{primary.contrast.color}",
      //   hoverColor: "{primary.contrast.color}",
      //   activeColor: "{primary.contrast.color}",
      //   focusRing: {
      //     color: "{uvGreen.600}",
      //     shadow: "none",
      //   },
      // },
      info: {
        background: "{uvTeal.300}",
        hoverBackground: "{uvTeal.200}",
        activeBackground: "{uvTeal.300}",
        borderColor: "{uvTeal.300}",
        hoverBorderColor: "{uvTeal.200}",
        activeBorderColor: "{uvTeal.300}",
        color: "{primary.contrast.color}",
        hoverColor: "{primary.contrast.color}",
        activeColor: "{primary.contrast.color}",
        focusRing: {
          color: "{uvTeal.500}",
          shadow: "none",
        },
      },
      success: {
        background: "{uvGreen.500}",
        hoverBackground: "{uvGreen.400}",
        activeBackground: "{uvGreen.500}",
        borderColor: "{uvGreen.500}",
        hoverBorderColor: "{uvGreen.400}",
        activeBorderColor: "{uvGreen.500}",
        color: "{primary.contrast.color}",
        hoverColor: "{primary.contrast.color}",
        activeColor: "{primary.contrast.color}",
        focusRing: {
          color: "{uvGreen.500}",
          shadow: "none",
        },
      },
      warn: {
        background: "{uvOrange.300}",
        hoverBackground: "{uvOrange.200}",
        activeBackground: "{uvOrange.300}",
        borderColor: "{uvOrange.300}",
        hoverBorderColor: "{uvOrange.200}",
        activeBorderColor: "{uvOrange.300}",
        color: "{primary.surface.950}",
        hoverColor: "{primary.surface.950}",
        activeColor: "{primary.surface.950}",
        focusRing: {
          color: "{uvOrange.500}",
          shadow: "none",
        },
      },
      help: {
        background: "{uvViolet.300}",
        hoverBackground: "{uvViolet.200}",
        activeBackground: "{uvViolet.300}",
        borderColor: "{uvViolet.300}",
        hoverBorderColor: "{uvViolet.200}",
        activeBorderColor: "{uvViolet.300}",
        color: "{primary.contrast.color}",
        hoverColor: "{primary.contrast.color}",
        activeColor: "{primary.contrast.color}",
        focusRing: {
          color: "{uvViolet.500}",
          shadow: "none",
        },
      },
      danger: {
        background: "{uvRed.500}",
        hoverBackground: "{uvRed.400}",
        activeBackground: "{uvRed.500}",
        borderColor: "{uvRed.400}",
        hoverBorderColor: "{uvRed.400}",
        activeBorderColor: "{uvRed.500}",
        color: "#ffffff",
        hoverColor: "#ffffff",
        activeColor: "#ffffff",
        focusRing: {
          color: "{uvRed.500}",
          shadow: "none",
        },
      },
      //   contrast: {
      //     background: "{surface.950}",
      //     hoverBackground: "{surface.900}",
      //     activeBackground: "{surface.800}",
      //     borderColor: "{surface.950}",
      //     hoverBorderColor: "{surface.900}",
      //     activeBorderColor: "{surface.800}",
      //     color: "{surface.0}",
      //     hoverColor: "{surface.0}",
      //     activeColor: "{surface.0}",
      //     focusRing: {
      //       color: "{surface.950}",
      //       shadow: "none",
      //     },
      //   },
    },
    outlined: {
      primary: {
        hoverBackground: "{primary.100}",
        activeBackground: "{primary.200}",
        borderColor: "{primary.300}",
        color: "{surface.950}",
      },
      // secondary: {
      //   hoverBackground: "{uvGreen.100}",
      //   activeBackground: "{uvGreen.200}",
      //   borderColor: "{uvGreen.300}",
      //   color: "{surface.950}",
      // },
      success: {
        hoverBackground: "{uvGreen.200}",
        activeBackground: "{uvGreen.400}",
        borderColor: "{uvGreen.500}",
        color: "{surface.950}",
      },
      info: {
        hoverBackground: "{uvTeal.100}",
        activeBackground: "{uvTeal.200}",
        borderColor: "{uvTeal.300}",
        color: "{surface.950}",
      },
      warn: {
        hoverBackground: "{uvOrange.100}",
        activeBackground: "{uvOrange.200}",
        borderColor: "{uvOrange.300}",
        color: "{surface.950}",
      },
      help: {
        hoverBackground: "{uvViolet.100}",
        activeBackground: "{uvViolet.200}",
        borderColor: "{uvViolet.300}",
        color: "{surface.950}",
      },
      danger: {
        hoverBackground: "{uvRed.100}",
        activeBackground: "{uvRed.200}",
        borderColor: "{uvRed.300}",
        color: "{surface.950}",
      },
      //   contrast: {
      //     hoverBackground: "{surface.50}",
      //     activeBackground: "{surface.100}",
      //     borderColor: "{surface.700}",
      //     color: "{primary.contrast.color}",
      //   },
      //   plain: {
      //     hoverBackground: "{surface.50}",
      //     activeBackground: "{surface.100}",
      //     borderColor: "{surface.200}",
      //     color: "{primary.contrast.color}",
      //   },
    },
    text: {
      primary: {
        hoverBackground: "{primary.50}",
        activeBackground: "{primary.100}",
        color: "{primary.color}",
      },
      // secondary: {
      //   hoverBackground: "{uvGreen.50}",
      //   activeBackground: "{uvGreen.100}",
      //   color: "{uvGreen.300}",
      // },
      success: {
        hoverBackground: "{uvGreen.200}",
        activeBackground: "{uvGreen.300}",
        color: "{uvGreen.500}",
      },
      info: {
        hoverBackground: "{uvTeal.50}",
        activeBackground: "{uvTeal.100}",
        color: "{uvTeal.300}",
      },
      warn: {
        hoverBackground: "{uvOrange.50}",
        activeBackground: "{uvOrange.100}",
        color: "{uvOrange.300}",
      },
      help: {
        hoverBackground: "{uvViolet.50}",
        activeBackground: "{uvViolet.100}",
        color: "{uvViolet.300}",
      },
      danger: {
        hoverBackground: "{uvRed.50}",
        activeBackground: "{uvRed.100}",
        color: "{uvRed.300}",
      },
      //   contrast: {
      //     hoverBackground: "{surface.50}",
      //     activeBackground: "{surface.100}",
      //     color: "{surface.950}",
      //   },
      //   plain: {
      //     hoverBackground: "{surface.50}",
      //     activeBackground: "{surface.100}",
      //     color: "{surface.700}",
      //   },
    },
    link: {
      color: "{primary.color}",
      hoverColor: "{primary.color}",
      activeColor: "{primary.color}",
    },
  },
  //   dark: {
  //     root: {
  //       primary: {
  //         background: "{primary.color}",
  //         hoverBackground: "{primary.hover.color}",
  //         activeBackground: "{primary.active.color}",
  //         borderColor: "{primary.color}",
  //         hoverBorderColor: "{primary.hover.color}",
  //         activeBorderColor: "{primary.active.color}",
  //         color: "{primary.contrast.color}",
  //         hoverColor: "{primary.contrast.color}",
  //         activeColor: "{primary.contrast.color}",
  //         focusRing: {
  //           color: "{primary.color}",
  //           shadow: "none",
  //         },
  //       },
  //       secondary: {
  //         background: "{surface.800}",
  //         hoverBackground: "{surface.700}",
  //         activeBackground: "{surface.600}",
  //         borderColor: "{surface.800}",
  //         hoverBorderColor: "{surface.700}",
  //         activeBorderColor: "{surface.600}",
  //         color: "{surface.300}",
  //         hoverColor: "{surface.200}",
  //         activeColor: "{surface.100}",
  //         focusRing: {
  //           color: "{surface.300}",
  //           shadow: "none",
  //         },
  //       },
  //       info: {
  //         background: "{sky.400}",
  //         hoverBackground: "{sky.300}",
  //         activeBackground: "{sky.200}",
  //         borderColor: "{sky.400}",
  //         hoverBorderColor: "{sky.300}",
  //         activeBorderColor: "{sky.200}",
  //         color: "{sky.950}",
  //         hoverColor: "{sky.950}",
  //         activeColor: "{sky.950}",
  //         focusRing: {
  //           color: "{sky.400}",
  //           shadow: "none",
  //         },
  //       },
  //       success: {
  //         background: "{green.400}",
  //         hoverBackground: "{green.300}",
  //         activeBackground: "{green.200}",
  //         borderColor: "{green.400}",
  //         hoverBorderColor: "{green.300}",
  //         activeBorderColor: "{green.200}",
  //         color: "{green.950}",
  //         hoverColor: "{green.950}",
  //         activeColor: "{green.950}",
  //         focusRing: {
  //           color: "{green.400}",
  //           shadow: "none",
  //         },
  //       },
  //       warn: {
  //         background: "{orange.400}",
  //         hoverBackground: "{orange.300}",
  //         activeBackground: "{orange.200}",
  //         borderColor: "{orange.400}",
  //         hoverBorderColor: "{orange.300}",
  //         activeBorderColor: "{orange.200}",
  //         color: "{orange.950}",
  //         hoverColor: "{orange.950}",
  //         activeColor: "{orange.950}",
  //         focusRing: {
  //           color: "{orange.400}",
  //           shadow: "none",
  //         },
  //       },
  //       help: {
  //         background: "{purple.400}",
  //         hoverBackground: "{purple.300}",
  //         activeBackground: "{purple.200}",
  //         borderColor: "{purple.400}",
  //         hoverBorderColor: "{purple.300}",
  //         activeBorderColor: "{purple.200}",
  //         color: "{purple.950}",
  //         hoverColor: "{purple.950}",
  //         activeColor: "{purple.950}",
  //         focusRing: {
  //           color: "{purple.400}",
  //           shadow: "none",
  //         },
  //       },
  //       danger: {
  //         background: "{red.400}",
  //         hoverBackground: "{red.300}",
  //         activeBackground: "{red.200}",
  //         borderColor: "{red.400}",
  //         hoverBorderColor: "{red.300}",
  //         activeBorderColor: "{red.200}",
  //         color: "{red.950}",
  //         hoverColor: "{red.950}",
  //         activeColor: "{red.950}",
  //         focusRing: {
  //           color: "{red.400}",
  //           shadow: "none",
  //         },
  //       },
  //       contrast: {
  //         background: "{surface.0}",
  //         hoverBackground: "{surface.100}",
  //         activeBackground: "{surface.200}",
  //         borderColor: "{surface.0}",
  //         hoverBorderColor: "{surface.100}",
  //         activeBorderColor: "{surface.200}",
  //         color: "{surface.950}",
  //         hoverColor: "{surface.950}",
  //         activeColor: "{surface.950}",
  //         focusRing: {
  //           color: "{surface.0}",
  //           shadow: "none",
  //         },
  //       },
  //     },
  //     outlined: {
  //       primary: {
  //         hoverBackground: "color-mix(in srgb, {primary.color}, transparent 96%)",
  //         activeBackground:
  //           "color-mix(in srgb, {primary.color}, transparent 84%)",
  //         borderColor: "{primary.700}",
  //         color: "{primary.color}",
  //       },
  //       secondary: {
  //         hoverBackground: "rgba(255,255,255,0.04)",
  //         activeBackground: "rgba(255,255,255,0.16)",
  //         borderColor: "{surface.700}",
  //         color: "{surface.400}",
  //       },
  //       success: {
  //         hoverBackground: "color-mix(in srgb, {green.400}, transparent 96%)",
  //         activeBackground: "color-mix(in srgb, {green.400}, transparent 84%)",
  //         borderColor: "{green.700}",
  //         color: "{green.400}",
  //       },
  //       info: {
  //         hoverBackground: "color-mix(in srgb, {sky.400}, transparent 96%)",
  //         activeBackground: "color-mix(in srgb, {sky.400}, transparent 84%)",
  //         borderColor: "{sky.700}",
  //         color: "{sky.400}",
  //       },
  //       warn: {
  //         hoverBackground: "color-mix(in srgb, {orange.400}, transparent 96%)",
  //         activeBackground: "color-mix(in srgb, {orange.400}, transparent 84%)",
  //         borderColor: "{orange.700}",
  //         color: "{orange.400}",
  //       },
  //       help: {
  //         hoverBackground: "color-mix(in srgb, {purple.400}, transparent 96%)",
  //         activeBackground: "color-mix(in srgb, {purple.400}, transparent 84%)",
  //         borderColor: "{purple.700}",
  //         color: "{purple.400}",
  //       },
  //       danger: {
  //         hoverBackground: "color-mix(in srgb, {red.400}, transparent 96%)",
  //         activeBackground: "color-mix(in srgb, {red.400}, transparent 84%)",
  //         borderColor: "{red.700}",
  //         color: "{red.400}",
  //       },
  //       contrast: {
  //         hoverBackground: "{surface.800}",
  //         activeBackground: "{surface.700}",
  //         borderColor: "{surface.500}",
  //         color: "{surface.0}",
  //       },
  //       plain: {
  //         hoverBackground: "{surface.800}",
  //         activeBackground: "{surface.700}",
  //         borderColor: "{surface.600}",
  //         color: "{surface.0}",
  //       },
  //     },
  //     text: {
  //       primary: {
  //         hoverBackground: "color-mix(in srgb, {primary.color}, transparent 96%)",
  //         activeBackground:
  //           "color-mix(in srgb, {primary.color}, transparent 84%)",
  //         color: "{primary.color}",
  //       },
  //       secondary: {
  //         hoverBackground: "{surface.800}",
  //         activeBackground: "{surface.700}",
  //         color: "{surface.400}",
  //       },
  //       success: {
  //         hoverBackground: "color-mix(in srgb, {green.400}, transparent 96%)",
  //         activeBackground: "color-mix(in srgb, {green.400}, transparent 84%)",
  //         color: "{green.400}",
  //       },
  //       info: {
  //         hoverBackground: "color-mix(in srgb, {sky.400}, transparent 96%)",
  //         activeBackground: "color-mix(in srgb, {sky.400}, transparent 84%)",
  //         color: "{sky.400}",
  //       },
  //       warn: {
  //         hoverBackground: "color-mix(in srgb, {orange.400}, transparent 96%)",
  //         activeBackground: "color-mix(in srgb, {orange.400}, transparent 84%)",
  //         color: "{orange.400}",
  //       },
  //       help: {
  //         hoverBackground: "color-mix(in srgb, {purple.400}, transparent 96%)",
  //         activeBackground: "color-mix(in srgb, {purple.400}, transparent 84%)",
  //         color: "{purple.400}",
  //       },
  //       danger: {
  //         hoverBackground: "color-mix(in srgb, {red.400}, transparent 96%)",
  //         activeBackground: "color-mix(in srgb, {red.400}, transparent 84%)",
  //         color: "{red.400}",
  //       },
  //       contrast: {
  //         hoverBackground: "{surface.800}",
  //         activeBackground: "{surface.700}",
  //         color: "{surface.0}",
  //       },
  //       plain: {
  //         hoverBackground: "{surface.800}",
  //         activeBackground: "{surface.700}",
  //         color: "{surface.0}",
  //       },
  //     },
  //     link: {
  //       color: "{primary.color}",
  //       hoverColor: "{primary.color}",
  //       activeColor: "{primary.color}",
  //     },
  //   },
};

export default {
  root,
  colorScheme,
} satisfies ButtonDesignTokens;
