/**
 * Application contract — groups the generated oRPC procedure contracts into
 * the same shape as the router so implement() can enforce them end-to-end.
 */
import {
    getStatus,
    listUsers,
    createUser,
    listGroups,
    getGroup,
    listGroupChildren,
    listGroupHierarchy,
    createGroup,
    updateGroup,
    replaceGroup,
    deleteGroup,
    listGroupPermissions,
    createGroupPermission,
    patchGroupPermission,
    deleteGroupPermission,
    listForms,
    getForm,
    createForm,
    updateForm,
    replaceForm,
    deleteForm,
    getFormLatestSchema,
    importFormSchema,
    getFormLatestSchemaJsonUi,
    importFormSchemaJsonUi,
    listFormPermissions,
    createFormPermission,
    patchFormPermission,
    deleteFormPermission,
    listApiKeys,
    createApiKey,
    deleteApiKey,
    patchApiKey,
    listFormVersions,
    createFormVersion,
    getFormSchemaByVersion,
    getFormSchemaVersionArtifacts,
} from './generated/orpc.gen';

export const appContract = {
    status: { get: getStatus },
    users: { create: createUser, list: listUsers },
    groups: {
        list: listGroups,
        get: getGroup,
        listChildren: listGroupChildren,
        hierarchy: listGroupHierarchy,
        create: createGroup,
        update: updateGroup,
        replace: replaceGroup,
        delete: deleteGroup,
        permissions: {
            list: listGroupPermissions,
            create: createGroupPermission,
            patch: patchGroupPermission,
            delete: deleteGroupPermission,
        },
    },
    forms: {
        list: listForms,
        get: getForm,
        create: createForm,
        update: updateForm,
        replace: replaceForm,
        delete: deleteForm,
        schema: {
            getLatest: getFormLatestSchema,
            import: importFormSchema,
            getLatestJsonUi: getFormLatestSchemaJsonUi,
            importJsonUi: importFormSchemaJsonUi,
        },
        permissions: {
            list: listFormPermissions,
            create: createFormPermission,
            patch: patchFormPermission,
            delete: deleteFormPermission,
        },
        versions: {
            list: listFormVersions,
            create: createFormVersion,
            getByVersion: getFormSchemaByVersion,
            getVersionArtifacts: getFormSchemaVersionArtifacts,
        },
    },
    apiKeys: {
        list: listApiKeys,
        create: createApiKey,
        delete: deleteApiKey,
        patch: patchApiKey,
    },
};
