import {
    PrimaryGeneratedColumn,
    CreateDateColumn,
    UpdateDateColumn,
    DeleteDateColumn,
    ManyToOne,
    JoinColumn,
} from 'typeorm';
import { User } from './User';

/**
 * Base class for all entities that include an auto-generated primary key ID.
 */
export abstract class BaseEntity {
    @PrimaryGeneratedColumn()
    id!: number;
}

/**
 * Base class for entities that use a UUID primary key.
 * The UUID is generated by the database (PostgreSQL `gen_random_uuid()`).
 */
export abstract class BaseUuidEntity {
    @PrimaryGeneratedColumn('uuid')
    id!: string;
}

/**
 * Base class for entities that track when they were created/updated/deleted,
 */
export abstract class BaseTimestampedEntity extends BaseEntity {
    // timestamptz (not naive `timestamp`) so the stored instant is
    // unambiguous regardless of the client/server timezone.
    @CreateDateColumn({ type: 'timestamptz' })
    created!: Date;

    @UpdateDateColumn({ type: 'timestamptz' })
    updated!: Date;

    @DeleteDateColumn({ type: 'timestamptz', nullable: true })
    deleted!: Date | null;
}

/**
 * Base class for all entities that track who created/updated them
 * and when. Also includes basic types from BaseAuditedTimestampedEntity.
 */
export abstract class BaseAuditedEntity extends BaseTimestampedEntity {
    @ManyToOne(() => User, { nullable: true })
    @JoinColumn({ name: 'created_by' })
    created_by!: User | null;

    @ManyToOne(() => User, { nullable: true })
    @JoinColumn({ name: 'updated_by' })
    updated_by!: User | null;
}

/**
 * Base class for all entities that track when they were created/updated/deleted,
 */
export enum Visibility {
    Visible = 'visible',
    Private = 'private',
}

export abstract class BaseCreatedEntity extends BaseEntity {
    @CreateDateColumn({ type: 'timestamptz' })
    created!: Date;

    @ManyToOne(() => User, { nullable: true })
    @JoinColumn({ name: 'created_by' })
    created_by!: User | null;
}

/**
 * Base class for entities that track when they were created (UUID variant).
 */
export abstract class BaseUuidCreatedEntity extends BaseUuidEntity {
    @CreateDateColumn({ type: 'timestamptz' })
    created!: Date;

    @ManyToOne(() => User, { nullable: true })
    @JoinColumn({ name: 'created_by' })
    created_by!: User | null;
}
