name: Browserstack tests
on:
  release:
    types: [published]
  pull_request:
    branches:
      - master
jobs:
  browserstack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'BrowserStack Env Setup'
        uses: 'browserstack/github-actions/setup-env@master'
        with:
            username:  ${{ secrets.BROWSERSTACK_USERNAME }}
            access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      - name: 'Start BrowserStackLocal Tunnel'
        uses: 'browserstack/github-actions/setup-local@master'
        with:
          local-testing: start
          local-logging-level: all-logs
          local-identifier: random
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: 'Install & Start'
        run: |
          npm ci
          npm run serve:test & npx wait-on http://localhost:8088
      - run: npm run browserstack
      - name: 'Stop BrowserStackLocal'
        uses: 'browserstack/github-actions/setup-local@master'
        with:
          local-testing: stop
