name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: npm run serve:test
          wait-on: 'http://localhost:8088'
      - name: Archive test results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-results
          path: cypress/screenshots/*
          retention-days: 5
